APP-4683 ;- Improving search results
InsolvencyService/inss-individualinsolvencyregister pull request #152
Opened 2024-01-23 20:00 UTC by prabhat-inss

2024-01-24 09:53 UTC, WayneBusby requested changes
This implementation for Full Name puts an additional space into the string.  We need to do a check on whether the middle name is null as part of the concatenation.

2024-01-24 10:54 UTC, VasInsolvencyService commented on INSS.EIIR.Models/IndexModels/IndividualSearch.cs
> +
Could you add unit test for the fix

2024-01-26 11:04 UTC, VasInsolvencyService approved these changes

2024-01-26 11:08 UTC, prabhat-inss commented on INSS.EIIR.Models/IndexModels/IndividualSearch.cs
> +
Added unit test for this field

2024-02-01 12:20 UTC, WayneBusby approved these changes

2024-02-01 12:20 UTC, merged