Atu 84 admin update subscriber details
InsolvencyService/inss-individualinsolvencyregister pull request #73
Opened 2022-10-27 10:42 UTC by spartacus72

2022-10-27 11:03 UTC, lombardig-nomensa commented on INSS.EIIR.Web/Areas/Admin/Controllers/SubscriberController.cs
>              var subscriber = await _subscriberDataProvider.GetSubscriberByIdAsync($"{subscriberId}");
I thought we agreed new code would use the api's and not the data provider directly ?

2022-10-27 11:57 UTC, lombardig-nomensa commented
> I thought we agreed GFDI.Happy to apply the change if that's your desire

No we said we would have tech debt tickets for the existing code base but anything new would use the api's.

2022-10-27 13:48 UTC, spartacus72 commented
Technically, this code existed before we “agreed” that.  But no bother.  I will change it now

2022-10-28 12:24 UTC, glinsolvency requested changes

2022-10-28 12:24 UTC, glinsolvency commented on INSS.EIIR.Web/appsettings-template.json
> +    "BaseUrl": "https://func-uksouth-dev-eiir-searchservice.azurewebsites.net/api",
please remove

2022-10-28 12:47 UTC, jcoales-nomensa approved these changes

2022-10-28 14:14 UTC, glinsolvency approved these changes

2022-10-28 15:49 UTC, glinsolvency approved these changes

2022-10-28 15:53 UTC, merged